// GENERATED by src/features/greeter/sync-ui.sh — do not edit. Edit src/ui and re-run.
import QtQuick
import qs.config

// Material Design 3 Icon Button
Item {
    id: root

    // Button properties
    property string variant: "standard"  // standard, filled, tonal, outlined
    property string iconName: "star"
    property int iconSize: Tokens.iconSize.large  // 24dp default
    property color iconColor: defaultIconColor()

    // Size properties
    property int containerSize: 40
    property int touchTargetSize: Tokens.touchTarget.minimum  // 48dp

    // Signals
    signal clicked(var mouse)
    signal pressed()
    signal released()

    // Dimensions
    implicitWidth: touchTargetSize
    implicitHeight: touchTargetSize

    // Container
    Rectangle {
        id: container
        anchors.centerIn: parent
        width: containerSize
        height: containerSize
        radius: containerSize / 2

        color: containerColor()
        border.width: variant === "outlined" ? 1 : 0
        border.color: variant === "outlined"
                ? (root.enabled ? GreeterTheme.outline : Qt.alpha(GreeterTheme.onSurface, Tokens.state.disabledContainerOpacity))
                : "transparent"

        Behavior on color {
            ColorAnimation {
                duration: Tokens.motion.duration.short4
                easing.type: Tokens.motion.easing.standard
                easing.bezierCurve: Tokens.motion.easing.standardPoints
            }
        }

        // State layer
        StateLayer {
            layerColor: stateLayerColor()
            hovered: mouseArea.containsMouse
            pressed: mouseArea.pressed
        }

        // Icon
        MaterialIcon {
            anchors.centerIn: parent
            iconName: root.iconName
            fontSize: root.iconSize
            iconColor: root.enabled ? root.iconColor : Qt.alpha(root.iconColor, Tokens.state.disabledContentOpacity)
            backgroundColor: "transparent"
        }
    }

    // Mouse area (full touch target)
    MouseArea {
        id: mouseArea
        anchors.fill: parent
        hoverEnabled: true
        cursorShape: root.enabled ? Qt.PointingHandCursor : Qt.ArrowCursor
        enabled: root.enabled

        onClicked: function(mouse) {
            root.clicked(mouse)
        }

        onPressed: {
            root.pressed()
        }

        onReleased: {
            root.released()
        }
    }

    // Helper functions
    function containerColor() {
        if (!root.enabled) {
            // Filled/tonal show a faint disabled fill; standard/outlined stay transparent.
            return (variant === "filled" || variant === "tonal")
                ? Qt.alpha(GreeterTheme.onSurface, Tokens.state.disabledContainerOpacity)
                : "transparent"
        }

        switch (variant) {
        case "filled":
            return GreeterTheme.primary
        case "tonal":
            return GreeterTheme.secondaryContainer
        case "outlined":
        case "standard":
        default:
            return "transparent"
        }
    }

    function defaultIconColor() {
        switch (variant) {
        case "filled":
            return GreeterTheme.onPrimary
        case "tonal":
            return GreeterTheme.onSecondaryContainer
        case "outlined":
        case "standard":
        default:
            return GreeterTheme.onSurfaceVariant
        }
    }

    function stateLayerColor() {
        switch (variant) {
        case "filled":
            return GreeterTheme.onPrimary
        case "tonal":
            return GreeterTheme.onSecondaryContainer
        default:
            return GreeterTheme.onSurface
        }
    }
}
