// GENERATED by src/features/greeter/sync-ui.sh — do not edit. Edit src/ui and re-run.
import QtQuick
import qs.config

// Optimized Material Design 3 Text component
// Caches style lookups to avoid repeated property resolution
Text {
    id: root

    property string textStyle: "bodyMedium"
    property string colorRole: "onSurface"

    // ✅ Кэшируем style один раз при изменении textStyle
    readonly property var currentStyle: Tokens.typography[textStyle] || Tokens.typography.bodyMedium

    // ✅ Кэшируем color один раз при изменении colorRole
    readonly property color resolvedColor: GreeterTheme[colorRole] || GreeterTheme.onSurface

    // Автоматическое применение Material Design 3 типографики
    font.family: Tokens.typography.fontFamily
    // MD3 type-scale sizes are in sp → map to Qt pixelSize (DPI-independent),
    // NOT pointSize (which is physical points and varies with font DPI).
    font.pixelSize: currentStyle.size
    font.weight: currentStyle.weight
    font.letterSpacing: currentStyle.letterSpacing

    renderType: Text.NativeRendering // Улучшенное сглаживание шрифтов
    color: resolvedColor
}
