// GENERATED by src/features/greeter/sync-ui.sh — do not edit. Edit src/ui and re-run.
import QtQuick
import qs.config

// Material Design 3 text component. Style and color resolve once per
// textStyle/colorRole change (cached lookups, no per-frame resolution).
Text {
    id: root

    property string textStyle: "bodyMedium"
    property string colorRole: "onSurface"

    readonly property var currentStyle: Tokens.typography[textStyle] || Tokens.typography.bodyMedium
    readonly property color resolvedColor: GreeterTheme[colorRole] || GreeterTheme.onSurface

    font.family: Tokens.typography.fontFamily
    // MD3 type-scale sizes are in sp → map to Qt pixelSize (DPI-independent),
    // NOT pointSize (which is physical points and varies with font DPI).
    font.pixelSize: currentStyle.size
    font.weight: currentStyle.weight
    font.letterSpacing: currentStyle.letterSpacing

    renderType: Text.NativeRendering
    color: resolvedColor
}
