#!/usr/bin/env bash
# Regenerate the greeter's local UI kit (greeter/ui/*) from the canonical main kit.
#
# The greeter runs as a SEPARATE Quickshell process (greetd, pre-login, `greeter` user)
# with its own module roots (qs.ui / qs.config) and its own theme (GreeterTheme, seeded
# from greeter.json instead of the logged-in user's WallpaperManager/AppConfig). The
# component bodies, however, are identical to the main kit modulo a mechanical substitution:
#   - import qs.src.core.config  ->  import qs.config        (GreeterTheme lives in qs.config)
#   - import qs.src.ui.{feedback,base}  ->  (dropped; same-module in qs.ui)
#   - Theme.  ->  GreeterTheme.   /   Theme[ -> GreeterTheme[
#   - Tokens: AppConfig.fontScale -> a literal (greeter has no AppConfig)
#
# This script is the single source of truth: edit src/ui, then re-run. Do not hand-edit
# greeter/ui/*.qml — changes will be overwritten.
#
# Usage:  src/features/greeter/sync-ui.sh   (run from anywhere)
set -euo pipefail

# Repo root = two levels up from this script (src/features/greeter -> repo root).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SRC="$ROOT/src/ui"
DST="$SCRIPT_DIR/ui"

# Greeter font scale (greeter has no AppConfig.fontScale binding). Keep in sync with the
# main shell's default fontScale (see config/default.json).
GREETER_FONT_SCALE="1.3"

HEADER="// GENERATED by src/features/greeter/sync-ui.sh — do not edit. Edit src/ui and re-run."

# component <source-relative-path>
components=(
  "MaterialText.qml:base/MaterialText.qml"
  "MaterialIcon.qml:base/MaterialIcon.qml"
  "MaterialButton.qml:base/MaterialButton.qml"
  "IconButton.qml:base/IconButton.qml"
  "CircleAvatar.qml:base/CircleAvatar.qml"
  "StateLayer.qml:feedback/StateLayer.qml"
)

# Common substitution applied to component files.
substitute() {
  sed -E \
    -e 's|import qs\.src\.core\.config|import qs.config|' \
    -e '/^import qs\.src\.ui\.feedback$/d' \
    -e '/^import qs\.src\.ui\.base$/d' \
    -e 's/\bTheme\b/GreeterTheme/g'
}

# Insert HEADER: after a leading `pragma` line if present, else at the very top.
with_header() {
  awk -v hdr="$HEADER" 'NR==1 && $0 ~ /^pragma/ {print; print hdr; next} NR==1 {print hdr} {print}'
}

for entry in "${components[@]}"; do
  out="${entry%%:*}"
  rel="${entry##*:}"
  substitute < "$SRC/$rel" | with_header > "$DST/$out"
  echo "  generated ui/$out  <- src/ui/$rel"
done

# Tokens: copy main tokens, drop the AppConfig dependency.
sed -E "s|AppConfig\.fontScale|$GREETER_FONT_SCALE|" "$ROOT/src/core/config/Tokens.qml" \
  | with_header > "$DST/Tokens.qml"
echo "  generated ui/Tokens.qml  <- src/core/config/Tokens.qml (fontScale=$GREETER_FONT_SCALE)"

echo "Done. Greeter UI kit regenerated in $DST"
